
api:
  version: 1.0

swagger:  
  enabled: true
  title: stores API
  description: API to find a store nearby.
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false;

ctp:
  projectKey: ${ctp.projectKey}
  clientId: ${ctp.clientId}
  clientSecret: ${ctp.clientSecret}
  authUrl: ${ctp.authUrl}
  apiUrl: ${ctp.apiUrl}

google:
  apikey: ${google.api.key}
