
api:
  version: 1.0

swagger:  
  enabled: true
  title: stores API
  description: API to find a store nearby.
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false;

ctp:
  projectKey: wirvsvirusshop
  clientId: run-with-profile-to-use-commerce-tools
  clientSecret: run-with-profile-to-use-commerce-tools
  authUrl: https://run-with-profile-to-use-commerce-tools.de
  apiUrl: https://run-with-profile-to-use-commerce-tools.de

google:
  apiKey: run-with-profile

#ctp:
#  projectKey: ${ctp.projectKey}
#  clientId: ${ctp.clientId}
#  clientSecret: ${ctp.clientSecret}
#  authUrl: ${ctp.authUrl}
#  apiUrl: ${ctp.apiUrl}

#google:
#  apiKey: ${google.apiKey}

auth:
  basic:
    user: ${auth.basic.user}
    password: ${auth.basic.password}

