# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Maven
      env:
        google.api.key: "1234"
        ctp.projectKey: "1234"
        ctp.clientId: "1234"
        ctp.clientSecret: "1234"
        ctp.authUrl: "1234"
        ctp.apiUrl: "1234"
      run: mvn package

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Sonar analysis
      env: 
        SONAR_API_KEY: ${{ secrets.SONAR_API_KEY }}
      run: mvn -B verify sonar:sonar -DskipTests -Dsonar.login=$SONAR_API_KEY -Dsonar.projectName=smallbusinesshero_dds-wvv-backend -Dsonar.branch.name=${GITHUB_REF##*/}
